version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing umps3
          command: |
            sudo add-apt-repository universe
            sudo apt update
            sudo add-apt-repository ppa:virtualsquare/umps
            sudo apt update
            sudo apt install umps3
      - run:
          name: Building
          command : |
            ./configure.sh
            ./build.sh

  docs:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Transferring docs
          command : |
            pwd
            cd ..
            git clone https://github.com/pandOSUnibo/docs
            rm -rf docs/docs
            cp -r project/docs docs/docs
            cd docs
            git push
            

workflows:
  default:
    jobs:
      - docs
      - build