version: 2.1
jobs:
  install:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing umps3
          command: |
            sudo add-apt-repository universe
            sudo apt update
            sudo add-apt-repository ppa:virtualsquare/umps
            sudo apt update
            sudo apt install umps3
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Building
          command : |
            cd build
            make

workflows:
  default:
    jobs:
      - install
      - build:
          requires:
            - install